[package]
name = "rust_qr"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
qrcode = "0.12"
dotenv = "0.15.0"
log = "0.4"
env_logger = "0.10"

[dev-dependencies]
rocket = { version = "0.5.0", features = ["json"] }